version: "3.3"

services:
  performance_testing:
    image: performance-testing:latest
    command: python run.py
    env_file:
      - .env
    volumes:
      - ./:/root/test
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    driver: bridge
